# Generated by Django 5.2.15 on 2026-07-02 17:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('ipa', models.CharField(blank=True, max_length=100)),
                ('meaning_vi', models.CharField(blank=True, max_length=500)),
                ('example_en', models.CharField(blank=True, max_length=1000)),
                ('example_vi', models.CharField(blank=True, max_length=1000)),
                ('raw_response', models.JSONField(blank=True, help_text='Full provider output, kept for future migrations.', null=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'word caches',
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('visibility', models.CharField(choices=[('private', 'Private')], default='private', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word_text', models.CharField(max_length=64)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('ipa', models.CharField(blank=True, max_length=100)),
                ('meaning_vi', models.CharField(blank=True, max_length=500)),
                ('example_en', models.CharField(blank=True, max_length=1000)),
                ('example_vi', models.CharField(blank=True, max_length=1000)),
                ('enrichment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('ease_factor', models.FloatField(default=2.5, validators=[django.core.validators.MinValueValidator(1.3)])),
                ('interval_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('repetitions', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocab.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to=settings.AUTH_USER_MODEL)),
                ('word_cache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_words', to='vocab.wordcache')),
            ],
        ),
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='deck_unique_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='userword',
            constraint=models.UniqueConstraint(fields=('deck', 'word_text'), name='userword_unique_deck_word_text'),
        ),
        migrations.AddConstraint(
            model_name='userword',
            constraint=models.CheckConstraint(condition=models.Q(('ease_factor__gte', 1.3)), name='userword_ease_factor_floor'),
        ),
        migrations.AddConstraint(
            model_name='userword',
            constraint=models.CheckConstraint(condition=models.Q(('interval_days__gte', 0), ('repetitions__gte', 0)), name='userword_srs_counters_non_negative'),
        ),
    ]
