# Generated by Django 5.2.15 on 2026-07-15 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_starter',
            field=models.BooleanField(default=False, help_text='System-curated deck offered to every user for cloning (SPEC §17.2-3).'),
        ),
        migrations.AddField(
            model_name='deck',
            name='source_deck',
            field=models.ForeignKey(blank=True, help_text='The deck this one was cloned from; also hides already-cloned starters.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='vocab.deck'),
        ),
    ]
