# Generated by Django 5.2.15 on 2026-07-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_deck_is_starter_deck_source_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
