# Generated by Django 5.2.15 on 2026-07-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlog',
            name='mode',
            field=models.CharField(choices=[('classic', 'Classic (typing + flip)'), ('mcq', 'Multiple choice'), ('listening', 'Listening (type what you hear)')], default='classic', max_length=10),
        ),
    ]
